[package]
name = "rz-assets"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
#cri-archive-lib = { path = "../../../cri-archive-lib/cri-archive-lib", features = ["cpk_compression_layla"] }
cri-archive-lib = { git = "https://github.com/hiroshil/cri-archive-lib", rev = "7434028d669fda28e36f1968e5bb99cf8303e24c", features = ["cpk_compression_layla"] }
flate2 = "1"
image = { version = "0.25", default-features = false, features = ["png"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
